# TCL File Generated by Component Editor 18.1
# Thu Feb 08 19:19:09 CET 2024
# DO NOT MODIFY


# 
# acc_scale "acc_scale" v1.0
# Lazar Premovic 2024.02.08.19:19:09
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module acc_scale
# 
set_module_property DESCRIPTION ""
set_module_property NAME acc_scale
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Accelerators
set_module_property AUTHOR "Lazar Premovic"
set_module_property DISPLAY_NAME acc_scale
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL acc_scale
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file acc_scale.vhd VHDL PATH hdl/acc_scale.vhd TOP_LEVEL_FILE
add_fileset_file line_buffer.vhd VHDL PATH hdl/line_buffer.vhd
add_fileset_file components.vhd VHDL PATH hdl/components.vhd
add_fileset_file image_counter.vhd VHDL PATH hdl/image_counter.vhd


# 
# parameters
# 
add_parameter max_width INTEGER 1024 ""
set_parameter_property max_width DEFAULT_VALUE 1024
set_parameter_property max_width DISPLAY_NAME max_width
set_parameter_property max_width WIDTH ""
set_parameter_property max_width TYPE INTEGER
set_parameter_property max_width UNITS None
set_parameter_property max_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property max_width DESCRIPTION ""
set_parameter_property max_width AFFECTS_GENERATION false


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst reset Input 1


# 
# connection point asi
# 
add_interface asi avalon_streaming end
set_interface_property asi associatedClock clock
set_interface_property asi associatedReset reset
set_interface_property asi dataBitsPerSymbol 8
set_interface_property asi errorDescriptor ""
set_interface_property asi firstSymbolInHighOrderBits true
set_interface_property asi maxChannel 0
set_interface_property asi readyLatency 0
set_interface_property asi ENABLED true
set_interface_property asi EXPORT_OF ""
set_interface_property asi PORT_NAME_MAP ""
set_interface_property asi CMSIS_SVD_VARIABLES ""
set_interface_property asi SVD_ADDRESS_GROUP ""

add_interface_port asi asi_data data Input 8
add_interface_port asi asi_ready ready Output 1
add_interface_port asi asi_valid valid Input 1
add_interface_port asi asi_eop endofpacket Input 1
add_interface_port asi asi_sop startofpacket Input 1


# 
# connection point aso
# 
add_interface aso avalon_streaming start
set_interface_property aso associatedClock clock
set_interface_property aso associatedReset reset
set_interface_property aso dataBitsPerSymbol 8
set_interface_property aso errorDescriptor ""
set_interface_property aso firstSymbolInHighOrderBits true
set_interface_property aso maxChannel 0
set_interface_property aso readyLatency 0
set_interface_property aso ENABLED true
set_interface_property aso EXPORT_OF ""
set_interface_property aso PORT_NAME_MAP ""
set_interface_property aso CMSIS_SVD_VARIABLES ""
set_interface_property aso SVD_ADDRESS_GROUP ""

add_interface_port aso aso_data data Output 8
add_interface_port aso aso_ready ready Input 1
add_interface_port aso aso_valid valid Output 1
add_interface_port aso aso_eop endofpacket Output 1
add_interface_port aso aso_sop startofpacket Output 1


# 
# connection point amms
# 
add_interface amms avalon end
set_interface_property amms addressUnits WORDS
set_interface_property amms associatedClock clock
set_interface_property amms associatedReset reset
set_interface_property amms bitsPerSymbol 8
set_interface_property amms bridgedAddressOffset 0
set_interface_property amms burstOnBurstBoundariesOnly false
set_interface_property amms burstcountUnits WORDS
set_interface_property amms explicitAddressSpan 0
set_interface_property amms holdTime 0
set_interface_property amms linewrapBursts false
set_interface_property amms maximumPendingReadTransactions 0
set_interface_property amms maximumPendingWriteTransactions 0
set_interface_property amms readLatency 0
set_interface_property amms readWaitTime 1
set_interface_property amms setupTime 0
set_interface_property amms timingUnits Cycles
set_interface_property amms writeWaitTime 0
set_interface_property amms ENABLED true
set_interface_property amms EXPORT_OF ""
set_interface_property amms PORT_NAME_MAP ""
set_interface_property amms CMSIS_SVD_VARIABLES ""
set_interface_property amms SVD_ADDRESS_GROUP ""

add_interface_port amms amms_address address Input 1
add_interface_port amms amms_read read Input 1
add_interface_port amms amms_readdata readdata Output 32
add_interface_port amms amms_write write Input 1
add_interface_port amms amms_writedata writedata Input 32
add_interface_port amms amms_waitrequest waitrequest Output 1
set_interface_assignment amms embeddedsw.configuration.isFlash 0
set_interface_assignment amms embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment amms embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment amms embeddedsw.configuration.isPrintableDevice 0

