/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_cpu' in SOPC Builder design 'system'
 * SOPC Builder design path: ../../system.sopcinfo
 *
 * Generated: Thu Feb 08 20:08:05 CET 2024
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x08000820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 100000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1c
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x04000020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 100000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x1c
#define ALT_CPU_NAME "nios2_cpu"
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x04000000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x08000820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 100000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x1c
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x04000020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x1c
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x04000000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ACC_SCALE
#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_NEW_SDRAM_CONTROLLER
#define __ALTERA_AVALON_PERFORMANCE_COUNTER
#define __ALTERA_AVALON_SGDMA
#define __ALTERA_NIOS2_GEN2


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone V"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart"
#define ALT_STDERR_BASE 0x8001100
#define ALT_STDERR_DEV jtag_uart
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart"
#define ALT_STDIN_BASE 0x8001100
#define ALT_STDIN_DEV jtag_uart
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart"
#define ALT_STDOUT_BASE 0x8001100
#define ALT_STDOUT_DEV jtag_uart
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "system"


/*
 * acc_scale configuration
 *
 */

#define ACC_SCALE_BASE 0x8001108
#define ACC_SCALE_IRQ -1
#define ACC_SCALE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ACC_SCALE_NAME "/dev/acc_scale"
#define ACC_SCALE_SPAN 8
#define ACC_SCALE_TYPE "acc_scale"
#define ALT_MODULE_CLASS_acc_scale acc_scale


/*
 * altera_hostfs configuration
 *
 */

#define ALTERA_HOSTFS_NAME "/mnt/host"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart altera_avalon_jtag_uart
#define JTAG_UART_BASE 0x8001100
#define JTAG_UART_IRQ 2
#define JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NAME "/dev/jtag_uart"
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_SPAN 8
#define JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


/*
 * perf_cnt configuration
 *
 */

#define ALT_MODULE_CLASS_perf_cnt altera_avalon_performance_counter
#define PERF_CNT_BASE 0x8001000
#define PERF_CNT_HOW_MANY_SECTIONS 7
#define PERF_CNT_IRQ -1
#define PERF_CNT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PERF_CNT_NAME "/dev/perf_cnt"
#define PERF_CNT_SPAN 128
#define PERF_CNT_TYPE "altera_avalon_performance_counter"


/*
 * sdram configuration
 *
 */

#define ALT_MODULE_CLASS_sdram altera_avalon_new_sdram_controller
#define SDRAM_BASE 0x4000000
#define SDRAM_CAS_LATENCY 2
#define SDRAM_CONTENTS_INFO
#define SDRAM_INIT_NOP_DELAY 0.0
#define SDRAM_INIT_REFRESH_COMMANDS 8
#define SDRAM_IRQ -1
#define SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_IS_INITIALIZED 1
#define SDRAM_NAME "/dev/sdram"
#define SDRAM_POWERUP_DELAY 100.0
#define SDRAM_REFRESH_PERIOD 7.8125
#define SDRAM_REGISTER_DATA_IN 1
#define SDRAM_SDRAM_ADDR_WIDTH 0x19
#define SDRAM_SDRAM_BANK_WIDTH 2
#define SDRAM_SDRAM_COL_WIDTH 10
#define SDRAM_SDRAM_DATA_WIDTH 16
#define SDRAM_SDRAM_NUM_BANKS 4
#define SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_SDRAM_ROW_WIDTH 13
#define SDRAM_SHARED_DATA 0
#define SDRAM_SIM_MODEL_BASE 0
#define SDRAM_SPAN 67108864
#define SDRAM_STARVATION_INDICATOR 0
#define SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define SDRAM_T_AC 5.4
#define SDRAM_T_MRD 3
#define SDRAM_T_RCD 15.0
#define SDRAM_T_RFC 60.0
#define SDRAM_T_RP 15.0
#define SDRAM_T_WR 14.0


/*
 * sdram configuration as viewed by sgdma_m2s_m_read
 *
 */

#define SGDMA_M2S_M_READ_SDRAM_BASE 0x4000000
#define SGDMA_M2S_M_READ_SDRAM_CAS_LATENCY 2
#define SGDMA_M2S_M_READ_SDRAM_CONTENTS_INFO
#define SGDMA_M2S_M_READ_SDRAM_INIT_NOP_DELAY 0.0
#define SGDMA_M2S_M_READ_SDRAM_INIT_REFRESH_COMMANDS 8
#define SGDMA_M2S_M_READ_SDRAM_IRQ -1
#define SGDMA_M2S_M_READ_SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_M2S_M_READ_SDRAM_IS_INITIALIZED 1
#define SGDMA_M2S_M_READ_SDRAM_NAME "/dev/sdram"
#define SGDMA_M2S_M_READ_SDRAM_POWERUP_DELAY 100.0
#define SGDMA_M2S_M_READ_SDRAM_REFRESH_PERIOD 7.8125
#define SGDMA_M2S_M_READ_SDRAM_REGISTER_DATA_IN 1
#define SGDMA_M2S_M_READ_SDRAM_SDRAM_ADDR_WIDTH 0x19
#define SGDMA_M2S_M_READ_SDRAM_SDRAM_BANK_WIDTH 2
#define SGDMA_M2S_M_READ_SDRAM_SDRAM_COL_WIDTH 10
#define SGDMA_M2S_M_READ_SDRAM_SDRAM_DATA_WIDTH 16
#define SGDMA_M2S_M_READ_SDRAM_SDRAM_NUM_BANKS 4
#define SGDMA_M2S_M_READ_SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define SGDMA_M2S_M_READ_SDRAM_SDRAM_ROW_WIDTH 13
#define SGDMA_M2S_M_READ_SDRAM_SHARED_DATA 0
#define SGDMA_M2S_M_READ_SDRAM_SIM_MODEL_BASE 0
#define SGDMA_M2S_M_READ_SDRAM_SPAN 67108864
#define SGDMA_M2S_M_READ_SDRAM_STARVATION_INDICATOR 0
#define SGDMA_M2S_M_READ_SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define SGDMA_M2S_M_READ_SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define SGDMA_M2S_M_READ_SDRAM_T_AC 5.4
#define SGDMA_M2S_M_READ_SDRAM_T_MRD 3
#define SGDMA_M2S_M_READ_SDRAM_T_RCD 15.0
#define SGDMA_M2S_M_READ_SDRAM_T_RFC 60.0
#define SGDMA_M2S_M_READ_SDRAM_T_RP 15.0
#define SGDMA_M2S_M_READ_SDRAM_T_WR 14.0


/*
 * sdram configuration as viewed by sgdma_s2m_m_write
 *
 */

#define SGDMA_S2M_M_WRITE_SDRAM_BASE 0x4000000
#define SGDMA_S2M_M_WRITE_SDRAM_CAS_LATENCY 2
#define SGDMA_S2M_M_WRITE_SDRAM_CONTENTS_INFO
#define SGDMA_S2M_M_WRITE_SDRAM_INIT_NOP_DELAY 0.0
#define SGDMA_S2M_M_WRITE_SDRAM_INIT_REFRESH_COMMANDS 8
#define SGDMA_S2M_M_WRITE_SDRAM_IRQ -1
#define SGDMA_S2M_M_WRITE_SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_S2M_M_WRITE_SDRAM_IS_INITIALIZED 1
#define SGDMA_S2M_M_WRITE_SDRAM_NAME "/dev/sdram"
#define SGDMA_S2M_M_WRITE_SDRAM_POWERUP_DELAY 100.0
#define SGDMA_S2M_M_WRITE_SDRAM_REFRESH_PERIOD 7.8125
#define SGDMA_S2M_M_WRITE_SDRAM_REGISTER_DATA_IN 1
#define SGDMA_S2M_M_WRITE_SDRAM_SDRAM_ADDR_WIDTH 0x19
#define SGDMA_S2M_M_WRITE_SDRAM_SDRAM_BANK_WIDTH 2
#define SGDMA_S2M_M_WRITE_SDRAM_SDRAM_COL_WIDTH 10
#define SGDMA_S2M_M_WRITE_SDRAM_SDRAM_DATA_WIDTH 16
#define SGDMA_S2M_M_WRITE_SDRAM_SDRAM_NUM_BANKS 4
#define SGDMA_S2M_M_WRITE_SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define SGDMA_S2M_M_WRITE_SDRAM_SDRAM_ROW_WIDTH 13
#define SGDMA_S2M_M_WRITE_SDRAM_SHARED_DATA 0
#define SGDMA_S2M_M_WRITE_SDRAM_SIM_MODEL_BASE 0
#define SGDMA_S2M_M_WRITE_SDRAM_SPAN 67108864
#define SGDMA_S2M_M_WRITE_SDRAM_STARVATION_INDICATOR 0
#define SGDMA_S2M_M_WRITE_SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define SGDMA_S2M_M_WRITE_SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define SGDMA_S2M_M_WRITE_SDRAM_T_AC 5.4
#define SGDMA_S2M_M_WRITE_SDRAM_T_MRD 3
#define SGDMA_S2M_M_WRITE_SDRAM_T_RCD 15.0
#define SGDMA_S2M_M_WRITE_SDRAM_T_RFC 60.0
#define SGDMA_S2M_M_WRITE_SDRAM_T_RP 15.0
#define SGDMA_S2M_M_WRITE_SDRAM_T_WR 14.0


/*
 * sgdma_m2s configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_m2s altera_avalon_sgdma
#define SGDMA_M2S_ADDRESS_WIDTH 32
#define SGDMA_M2S_ALWAYS_DO_MAX_BURST 1
#define SGDMA_M2S_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_M2S_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_M2S_BASE 0x80010c0
#define SGDMA_M2S_BURST_DATA_WIDTH 8
#define SGDMA_M2S_BURST_TRANSFER 0
#define SGDMA_M2S_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_M2S_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_M2S_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_M2S_CONTROL_DATA_WIDTH 8
#define SGDMA_M2S_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_M2S_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_M2S_DESCRIPTOR_READ_BURST 0
#define SGDMA_M2S_DESC_DATA_WIDTH 32
#define SGDMA_M2S_HAS_READ_BLOCK 1
#define SGDMA_M2S_HAS_WRITE_BLOCK 0
#define SGDMA_M2S_IN_ERROR_WIDTH 0
#define SGDMA_M2S_IRQ 0
#define SGDMA_M2S_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_M2S_NAME "/dev/sgdma_m2s"
#define SGDMA_M2S_OUT_ERROR_WIDTH 0
#define SGDMA_M2S_READ_BLOCK_DATA_WIDTH 8
#define SGDMA_M2S_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_M2S_SPAN 64
#define SGDMA_M2S_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_M2S_STREAM_DATA_WIDTH 8
#define SGDMA_M2S_SYMBOLS_PER_BEAT 1
#define SGDMA_M2S_TYPE "altera_avalon_sgdma"
#define SGDMA_M2S_UNALIGNED_TRANSFER 0
#define SGDMA_M2S_WRITE_BLOCK_DATA_WIDTH 8
#define SGDMA_M2S_WRITE_BURSTCOUNT_WIDTH 4


/*
 * sgdma_s2m configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_s2m altera_avalon_sgdma
#define SGDMA_S2M_ADDRESS_WIDTH 32
#define SGDMA_S2M_ALWAYS_DO_MAX_BURST 1
#define SGDMA_S2M_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_S2M_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_S2M_BASE 0x8001080
#define SGDMA_S2M_BURST_DATA_WIDTH 8
#define SGDMA_S2M_BURST_TRANSFER 0
#define SGDMA_S2M_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_S2M_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_S2M_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_S2M_CONTROL_DATA_WIDTH 8
#define SGDMA_S2M_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_S2M_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_S2M_DESCRIPTOR_READ_BURST 0
#define SGDMA_S2M_DESC_DATA_WIDTH 32
#define SGDMA_S2M_HAS_READ_BLOCK 0
#define SGDMA_S2M_HAS_WRITE_BLOCK 1
#define SGDMA_S2M_IN_ERROR_WIDTH 0
#define SGDMA_S2M_IRQ 1
#define SGDMA_S2M_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_S2M_NAME "/dev/sgdma_s2m"
#define SGDMA_S2M_OUT_ERROR_WIDTH 0
#define SGDMA_S2M_READ_BLOCK_DATA_WIDTH 8
#define SGDMA_S2M_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_S2M_SPAN 64
#define SGDMA_S2M_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_S2M_STREAM_DATA_WIDTH 8
#define SGDMA_S2M_SYMBOLS_PER_BEAT 1
#define SGDMA_S2M_TYPE "altera_avalon_sgdma"
#define SGDMA_S2M_UNALIGNED_TRANSFER 0
#define SGDMA_S2M_WRITE_BLOCK_DATA_WIDTH 8
#define SGDMA_S2M_WRITE_BURSTCOUNT_WIDTH 4

#endif /* __SYSTEM_H_ */
